version: '0.1'

services:
  extractionservice:
    image: extractionservice
    env_file: 
      - .env 
    build:
      context: . 
      dockerfile: ./Dockerfile
    ports:
      - 5002:8000
    volumes:
      - ./logfiles.log:/app/logfiles.log
      - ./client_secret.json:/app/client_secret.json


