# Generated by Django 4.2 on 2023-11-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gdrive", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
                ("expiry", models.CharField(max_length=255)),
                ("scopes", models.CharField(max_length=256)),
                ("token_uri", models.CharField(max_length=256)),
                ("client_id", models.CharField(max_length=256)),
                ("client_secret", models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name="Credentials",
        ),
    ]
